### ISSUE TITLE
New version of the Patentview API

### ISSUE THREAD

**Issue by mustberuss** [mikeym88/PatentsView-API-Wrapper#2]
Wasn't sure if you saw that they're working on a new version of the API and that they plan to shutdown the current version at the end of the year. They're changing a lot and requiring an API key https://patentsview.org/apis/api-endpoints

**Comment by mustberuss** [comment]
I got my fork to work with the new version of the API!  Wasn't sure if you were working on it too or if I should do a PR.

**Comment by mikeym88** [comment]
@mustberuss Nice! Create a PR and I'll review the changes. Thanks.

**Comment by mikeym88** [comment]
@mustberuss One of the problems that this repository is trying to remedy is the fact that the legacy API didn't recognize that two company names represented the same company. Do you know if the new API solves that problem?

**Comment by mustberuss** [comment]
They have improved their disambiguation algorithm, where they try to combine companies and inventors who they think are the same business or person.  From the README, now there is only one Netflix entry so they either combined them all under one or something is still messed up.  I should hit the old api and compare what they did.

I'll submit a PR now, not positive it's 100% but it does hit the new endpoints.  Note that you'll need to get an API key and set an environmental variable for it.  I updated the README but probably could have done a better job of explaining it.

thanks,
Russ

**Comment by mikeym88** [comment]
Merged the changes. Thanks for your contribution @mustberuss.
